### ISSUE TITLE
Settings only works in English

### ISSUE THREAD

**Issue by whisdol** [emoacht/HelloSwitcher#6] opened 2021-05-16 09:42 UTC
Hi,

I'm using a Surface Pro 4 with an external webcam ("USB2.0 FHD UVC WebCam") that is integrated into my display (Philips 499P9H). The camera works fine for Windows Hello on another laptop (Lenovo T470) without a built-in Hello camera.
After installing the HelloSwitcher tool, the settings app recognizes three cameras, but does not show their names:
![image](https://user-images.githubusercontent.com/5374166/118392281-2714d580-b639-11eb-9863-ef9427bbc14f.png)

I can switch between Built-in Camera/USB Camera and "Apply", but these settings are reset after opening the Settings again. 

Update: If I change my default language to English (US) (from German), the device names are displayed and the settings stick.

**Comment by emoacht** [comment] 2021-05-17 04:28
Thank you for reporting.
This is caused by parsing the outputs of PnPUtil. I have not noticed but under some culture settings of the OS, PnPUtil will produce language-specific outputs even if the code page is set to `en-US`.

I tested some cultures and found that the outputs will be:

- Language-specific: `de-DE`, `fr-FR`, `es-ES`, `it-IT`
  [PnPUtil_de-DE.txt](https://github.com/emoacht/HelloSwitcher/files/6498624/PnPUtil_de-DE.txt)
  [PnPUtil_fr-FR.txt](https://github.com/emoacht/HelloSwitcher/files/6498626/PnPUtil_fr-FR.txt) 
  [PnPUtil_es-ES.txt](https://github.com/emoacht/HelloSwitcher/files/6498625/PnPUtil_es-ES.txt)
  [PnPUtil_it-IT.txt](https://github.com/emoacht/HelloSwitcher/files/6498627/PnPUtil_it-IT.txt)

- English: `ja-JP`, `ru-RU`, `zh-Hans`, `zh-Hant`, `kr-KR`

I will make some modifications to parse language-specific outputs.

**Comment by emoacht** [comment] 2021-05-18 00:32
Fixed by 2d301cd5667bc3de65f3d6c3e205949a581cad17

**Closed as completed by emoacht** 2021-05-18 00:32 UTC
